name: Build, Push Docker Image to ECR, and Deploy to ECS
on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          IMAGE_REPO_NAME=aws-agent
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Push Docker image to Amazon ECR
        run: |
          IMAGE_TAG=latest
          IMAGE_REPO_NAME=aws-agent
          docker push ${{ steps.login-ecr.outputs.registry }}/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Log out of Amazon ECR
        run: |
          docker logout ${{ steps.login-ecr.outputs.registry }}

      - name: Force deploy to ECS
        run: |
          CLUSTER_NAME=hiaido-agent-cluster
          SERVICE_NAME=api-service
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
